// /etc directory structure
// System configuration files

export function createEtcDirectory() {
    return {
        'etc': {
            type: 'directory',
            permissions: '0755',
            owner: 'root',
            group: 'root',
            size: 4096,
            modified: new Date(),
            children: {
                'passwd': {
                    type: 'file',
                    permissions: '0644',
                    owner: 'root',
                    group: 'root',
                    size: 256,
                    modified: new Date(),
                    content: 'root:x:0:0:root:/root:/bin/bash\naaron:x:1000:1000:Aaron:/home/aaron:/bin/bash\nstudent:x:1001:1001:Student:/home/student:/bin/bash\n'
                },
                'group': {
                    type: 'file',
                    permissions: '0644',
                    owner: 'root',
                    group: 'root',
                    size: 128,
                    modified: new Date(),
                    content: 'root:x:0:\nwheel:x:10:root,aaron\naaron:x:1000:\nstudent:x:1001:\n'
                },
                'shadow': {
                    type: 'file',
                    permissions: '0000',
                    owner: 'root',
                    group: 'root',
                    size: 256,
                    modified: new Date(),
                    content: 'root:$6$encrypted:19000:0:99999:7:::\n'
                },
                'hosts': {
                    type: 'file',
                    permissions: '0644',
                    owner: 'root',
                    group: 'root',
                    size: 64,
                    modified: new Date(),
                    content: '127.0.0.1   localhost localhost.localdomain\n192.168.1.10 rhcsa-lab.example.com rhcsa-lab\n'
                },
                'hostname': {
                    type: 'file',
                    permissions: '0644',
                    owner: 'root',
                    group: 'root',
                    size: 10,
                    modified: new Date(),
                    content: 'rhcsa-lab\n'
                },
                'fstab': {
                    type: 'file',
                    permissions: '0644',
                    owner: 'root',
                    group: 'root',
                    size: 256,
                    modified: new Date(),
                    content: '# /etc/fstab\nUUID=1234-5678  /       xfs     defaults        0 0\nUUID=abcd-efgh  /boot   ext4    defaults        0 0\n'
                },
                'sudoers': {
                    type: 'file',
                    permissions: '0440',
                    owner: 'root',
                    group: 'root',
                    size: 128,
                    modified: new Date(),
                    content: 'root    ALL=(ALL)       ALL\n%wheel  ALL=(ALL)       ALL\n'
                },
                'resolv.conf': {
                    type: 'file',
                    permissions: '0644',
                    owner: 'root',
                    group: 'root',
                    size: 64,
                    modified: new Date(),
                    content: '# Generated by NetworkManager\nnameserver 8.8.8.8\nnameserver 8.8.4.4\n'
                },
                'ssh': {
                    type: 'directory',
                    permissions: '0755',
                    owner: 'root',
                    group: 'root',
                    size: 4096,
                    modified: new Date(),
                    children: {
                        'sshd_config': {
                            type: 'file',
                            permissions: '0600',
                            owner: 'root',
                            group: 'root',
                            size: 512,
                            modified: new Date(),
                            content: '# SSH daemon configuration\nPort 22\nPermitRootLogin yes\nPasswordAuthentication yes\nPubkeyAuthentication yes\n'
                        }
                    }
                },
                'selinux': {
                    type: 'directory',
                    permissions: '0755',
                    owner: 'root',
                    group: 'root',
                    size: 4096,
                    modified: new Date(),
                    children: {
                        'config': {
                            type: 'file',
                            permissions: '0644',
                            owner: 'root',
                            group: 'root',
                            size: 128,
                            modified: new Date(),
                            content: 'SELINUX=enforcing\nSELINUXTYPE=targeted\n'
                        }
                    }
                },
                'systemd': {
                    type: 'directory',
                    permissions: '0755',
                    owner: 'root',
                    group: 'root',
                    size: 4096,
                    modified: new Date(),
                    children: {
                        'system': {
                            type: 'directory',
                            permissions: '0755',
                            owner: 'root',
                            group: 'root',
                            size: 4096,
                            modified: new Date(),
                            children: {}
                        }
                    }
                },
                'yum.repos.d': {
                    type: 'directory',
                    permissions: '0755',
                    owner: 'root',
                    group: 'root',
                    size: 4096,
                    modified: new Date(),
                    children: {
                        'rhel.repo': {
                            type: 'file',
                            permissions: '0644',
                            owner: 'root',
                            group: 'root',
                            size: 256,
                            modified: new Date(),
                            content: '[rhel-9-baseos]\nname=Red Hat Enterprise Linux 9 - BaseOS\nbaseurl=https://cdn.redhat.com/content/dist/rhel9/\nenabled=1\ngpgcheck=1\n'
                        }
                    }
                },
                'cron.d': {
                    type: 'directory',
                    permissions: '0755',
                    owner: 'root',
                    group: 'root',
                    size: 4096,
                    modified: new Date(),
                    children: {}
                },
                'crontab': {
                    type: 'file',
                    permissions: '0644',
                    owner: 'root',
                    group: 'root',
                    size: 128,
                    modified: new Date(),
                    content: 'SHELL=/bin/bash\nPATH=/sbin:/bin:/usr/sbin:/usr/bin\n'
                }
            }
        }
    };
}
